DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS BIDS;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS CurrentTime;

CREATE TABLE USERS (
  UserID VARCHAR,
  Location VARCHAR,
  Country VARCHAR,
  Rating VARCHAR,
  PRIMARY KEY (userID)
);

CREATE TABLE ITEMS (
  ItemID INT,
  Name VARCHAR,
  Currently REAL,
  Buy_Price REAL,
  First_Bid REAL,
  Number_of_Bids INT,
  Started DATETIME,
  Ends DATETIME,
  SellerID VARCHAR,
  Description VARCHAR,
  PRIMARY KEY (itemID)
);


CREATE TABLE CATEGORIES (
  ItemID INTEGER,
  Category VARCHAR,
  PRIMARY KEY (itemID, category)
);

CREATE TABLE BIDS (
  ItemID INTEGER,
  BidderID VARCHAR,
  Amount REAL,
  Time DATETIME,
  PRIMARY KEY (BidderID, ItemID, Amount),
  FOREIGN KEY (BidderID) REFERENCES Users(UserID)
);

CREATE TABLE CurrentTime (
  Use_Current_Time DATETIME
);

INSERT INTO CurrentTime
VALUES('2001-12- 20 00:00:01');

SELECT * FROM CurrentTime;